### ISSUE TITLE
qt-components-hildon based apps can't be launched on Fremantle

### ISSUE THREAD

**Issue by marmistrz** [marxoft/qt-components-hildon#1]
Any app using qt-components-hildon can't be launched on CSSU Thumb Fremantle. See http://talk.maemo.org/showpost.php?p=1445332&postcount=179

**Comment by marmistrz** [comment]
But why does it happen with Thumb and not with Testing? They should be using the same Qt version, the thumb2 flags should be the only differences.

**Comment by marxoft** [comment]
They are the same Qt version, but compiling with thumb2 flags will affect the symbols, so including the private APIs in qt-components-hildon will break ABI compatibility with the thumb2 QtDeclarative library. Compiling qt-components-hildon for thumb2 should fix this.

**Comment by mickaelh** [comment]
hi, 
Just to help, i have a scratchbox armel and thumb flag.
I wanted to recompile "qt-components-hildon" and I get to the following error:

webview_p.h:256: Error: NOTIFY signal 'iconChanged' of property 'icon' does not exist in class WebView.

The class "WebView" depend of "libx11-dev" "libqt4-dev" which is every 2 installed. And no property, "icon" on the package

**Comment by marxoft** [comment]
Thanks for helping and for reporting the compiler errors. There were some errors in various properties declared using the Q_PROPERTY macro (typos etc), which were not reported when compiling for armel. I have now fixed these (will push commits later), and have successfully compiled qt-components-hildon for thumb: http://marxoft.co.uk/products/qt-components-hildon/qt-components-hildon_0.12.1_armel_gcc472.deb.

**Comment by vakkov** [comment]
Problem still persists with version 0.12.1. Tested with qml-browser; exactly the same output.

**Comment by android-808** [comment]
I tried to build on thumb the other day to see if I can find any reason for failing.  There appears to be another build issue with thumb version for me regarding the dbus componenets.  qdbusutil_p.h was causing problems because of QDBUS_EXPORT not being defined.  Looking into it, it appears the API changed in Qt 4.7.1 to align it with what everything else was using. Changing to Q_DBUS_EXPORT allowed it to build again.

First ref: https://github.com/marxoft/qt-components-hildon/blob/master/src/dbus/qdbusutil_p.h#L68

Unfortunately, it still quits on same error.  I did a little more digging, but it seems to me that the symbol is missing in qt.  Whether it has been built using different params I don't know at the moment but it seems Q_AUTOTEST_EXPORT may not be set.

**Comment by mickaelh** [comment]
Hello,

I managed to fix all the little problems and create the package-compatible thumb for N900

I am sending you make changes(http://talk.maemo.org/showpost.php?p=1463127&postcount=201).

I am part of this commit: 9c0774630165c4e622c3f4b4d8e8764d0b711427

**Comment by mickaelh** [comment]
hello,

I have a track for the plugins that do not load, with this error message:

QDeclarativeComponent: Component is not ready
"file:///opt/qml-browser/qml/main.qml:18:1: plugin cannot be loaded for module "org.hildon.components": Cannot load library /opt/lib/qt4/imports/org/hildon/components/libhildoncomponents.so: (/opt/lib/qt4/imports/org/hildon/components/libhildoncomponents.so: undefined symbol: _ZN16QDeclarativeBind10classBeginEv)"

This section explains :  http://michael-stengel.com/blog/?p=4

add "= 0" for virtual:
protected:
    virtual void classBegin() = 0;
    virtual void componentComplete() = 0;

after the compiler you an error message similar to:

 ***_/QtDeclarative/qdeclarativeprivate.h: In instantiation of 'void QDeclarativePrivate::createInto(void_) [with T = QDeclarativeBind]':
 ****/QtDeclarative/qdeclarative.h:188:5:   required from 'int qmlRegisterType(const char_, int, int, const char_) [with T = QDeclarativeBind]'
plugin.cpp:202:59:   required from here
 ***_/QtDeclarative/qdeclarativeprivate.h:91:37: error: cannot allocate an object of abstract type 'QDeclarativePrivate::QDeclarativeElement<QDeclarativeBind>'
 ***_/QtDeclarative/qdeclarativeprivate.h:82:11: note:   because the following virtual functions are pure within 'QDeclarativePrivate::QDeclarativeElement<QDeclarativeBind>':
In file included from plugin.cpp:75:0:
qdeclarativebind_p.h:83:18: note:   virtual void QDeclarativeBind::classBegin()
qdeclarativebind_p.h:84:18: note:   virtual void QDeclarativeBind::componentComplete()
qdeclarativebind_p.h:83:18: note:   virtual void QDeclarativeBind::classBegin()
qdeclarativebind_p.h:84:18: note:   virtual void QDeclarativeBind::componentComplete()

I hope its help you

**Comment by mickaelh** [comment]
Hello, 
notice to the developer. 
I am sending you the record of changes made and explanation of errors. 

As said in the article:
 http://michael-stengel.com/blog/?p=4

Some interfaface had no address, so the application could not the chargers.
To see the relevant interfaces, it is necessary to use this command:
nm -CD /path/qt-components-hildon/src/components/libhildoncomponents.so

**One obtains:**
         U QDeclarativeBind::classBegin()
0010ffc0 T QDeclarativeBind::qt_metacall(QMetaObject::Call, int, void*_)
0010ff30 T QDeclarativeBind::qt_metacast(char const_)
         U QDeclarativeBind::setProperty(QString const&)
001519d4 D QDeclarativeBind::staticMetaObject
         U QDeclarativeBind::componentComplete()
         U QDeclarativeBind::object()
000f7c04 W QDeclarativeBind::setObject(QObject_)
         U QDeclarativeBind::QDeclarativeBind(QObject_)
         U QDeclarativeBind::~QDeclarativeBind()
         U QDeclarativeBind::~QDeclarativeBind()
         U QDeclarativeBind::~QDeclarativeBind()
000fbba0 W void QDeclarativePrivate::createInto<QDeclarativeBind>(void*)
000fc9b0 W QDeclarativePrivate::QDeclarativeElement<QDeclarativeBind>::~QDeclarativeElement()

We note that some interfaces do not have an address.
Just changing the syntax: 
~QDeclarativeBind();
by 
virtual ~QDeclarativeBind() {};

**One obtains:**
000f7a78 W QDeclarativeBind::classBegin()
0010fe44 T QDeclarativeBind::qt_metacall(QMetaObject::Call, int, void*_)
0010fe9c T QDeclarativeBind::qt_metacast(char const_)
0015180c D QDeclarativeBind::staticMetaObject
000f7a84 W QDeclarativeBind::componentComplete()
         U QDeclarativeBind::object()
000f7a74 W QDeclarativeBind::setObject(QObject_)
         U QDeclarativeBind::QDeclarativeBind(QObject_)
000fe10c W QDeclarativeBind::~QDeclarativeBind()
000fe000 W QDeclarativeBind::~QDeclarativeBind()
000fe000 W QDeclarativeBind::~QDeclarativeBind()
000fb9e8 W void QDeclarativePrivate::createInto<QDeclarativeBind>(void*)
000fe0a4 W QDeclarativePrivate::QDeclarativeElement<QDeclarativeBind>::~QDeclarativeElement()

I commented on the Q_PROPERTY: when( ), value( ), property() 
it requires a particular integration using the macro Q_EXPORT_PLUGIN2

Obviously all remains a review. 
I am at your disposal if you need to compile compatible thumb, or even for the debug. 

Thank you for your understanding

**Comment by marmistrz** [comment]
Cross-reporting this issue: http://talk.maemo.org/showpost.php?p=1471332&postcount=227

**Comment by marxoft** [comment]
Qt Components Hildon no longer depends on private QtDeclarative APIs. :)

**Comment by marmistrz** [comment]
## Are you going to push it to extras-devel in the near future?

Ex mea Nokia N900 missum
Marcin

**Comment by android-808** [comment]
QDBUS_EXPORT vs Q_DBUS_EXPORT issue still exists when compiling on thumb.  Manually changing again allows build to complete.  I'm running into some issues with package building at the moment though -  dbus component is failing to install after qmldir element is installed.  First a message about not being able to remove dbus as it is a directory, then "exists but is not a directory" message straight after.  Non-thumb package builds fine.

Going to test on another build machine later.

**Comment by marmistrz** [comment]
@android-808 if you're using scratchbox apophis, try hathor and vice-versa. IIRC it helped while working with the embedlite browser replacement.
